name: CI pipeline

on:
    push:
        branches: [main, develop]
    pull_request:
        branches: [main, develop]

jobs:
    test:
        name: Run Integration Tests
        runs-on: ubuntu-latest
        
        services:
          postgres:
            image: postgres:16
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: test
              POSTGRES_DB: biblios_database_dev
            ports:
                - 5432:5432
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
        steps:
            #Check Out Code
            - uses: actions/checkout@v4

            #Install Python
            - uses: actions/setup-python@v5
              with:
                python-version: 3.11
            
            #Install Requirements.txt
            - working-directory: server
              run: |
                pip install -r requirements.txt
                pip install -r requirements_test.txt

            - name: Create postgres & load schemas
              env: 
                PGPASSWORD: test
              run: psql -h localhost -U postgres -d biblios_database_dev -f server/schema.sql

            - name: Run tests

              working-directory: server
              env:
                DATABASE_URL: postgresql://postgres:test@localhost:5432/biblios_database_dev
                SECRET_KEY: test-secret-key-doesnt-matter-for-this-test
              run: 
                pytest tests_python/ -v


            





